# Kapitel 1 – Colab und Python Basics

Dieses Notebook dient als technischer und inhaltlicher Einstieg in den Kurs.  
Wir arbeiten mit einfachen Python-Befehlen, Listen, NumPy, pandas und einer ersten Visualisierung.

## Lernziele
Nach diesem Notebook können Sie:
- einfache Python-Anweisungen ausführen,
- Listen und Schleifen verwenden,
- den Unterschied zwischen Liste, Array und DataFrame grob einordnen,
- eine einfache Tabelle erzeugen,
- eine erste Visualisierung mit Matplotlib erstellen.

## Abschnitt 1 – Erste Python-Befehle

Führen Sie die nächsten Zellen nacheinander aus und beobachten Sie jeweils die Ausgabe.

In [1]:
print("Hallo, Maschinelles Lernen!")
print("Dieses Notebook läuft erfolgreich.")

Hallo, Maschinelles Lernen!
Dieses Notebook läuft erfolgreich.

In [2]:
a = 7
b = 5

print("a =", a)
print("b =", b)
print("a + b =", a + b)
print("a * b =", a * b)

a = 7
b = 5
a + b = 12
a * b = 35

## Abschnitt 2 – Listen und Schleifen

Listen sind geordnete Sammlungen von Werten.  
Mit einer Schleife können wir über alle Elemente einer Liste nacheinander iterieren.

In [3]:
zahlen = [2, 4, 6, 8, 10]
print("Liste:", zahlen)
print("Erstes Element:", zahlen[0])
print("Anzahl Elemente:", len(zahlen))

Liste: [2, 4, 6, 8, 10]
Erstes Element: 2
Anzahl Elemente: 5

In [4]:
for z in zahlen:
    print("Quadrat von", z, "=", z**2)

Quadrat von 2 = 4
Quadrat von 4 = 16
Quadrat von 6 = 36
Quadrat von 8 = 64
Quadrat von 10 = 100

## Abschnitt 3 – Wichtige Bibliotheken importieren

In ML-Projekten arbeiten wir fast immer mit:
- **NumPy** für numerische Arrays,
- **pandas** für Tabellen,
- **Matplotlib** für Visualisierungen.

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print("NumPy-Array:", arr)
print("Datentyp:", type(arr))
print("Array mal 2:", arr * 2)

## Abschnitt 4 – Eine kleine Tabelle mit pandas

Ein **DataFrame** ist eine tabellarische Datenstruktur mit Zeilen und Spalten.  
So ähnlich werden später auch viele Datensätze im Machine Learning dargestellt.

In [7]:
df = pd.DataFrame({
    "Lernzeit_Stunden": [2, 4, 6, 8, 10],
    "Punktzahl": [50, 58, 68, 80, 92]
})

df

   Lernzeit_Stunden  Punktzahl
0                 2         50
1                 4         58
2                 6         68
3                 8         80
4                10         92

In [8]:
print("Form des DataFrames:", df.shape)
print()
print("Spaltennamen:", list(df.columns))
print()
print("Erste Zeilen:")
print(df.head())

Form des DataFrames: (5, 2)

Spaltennamen: ['Lernzeit_Stunden', 'Punktzahl']

Erste Zeilen:
   Lernzeit_Stunden  Punktzahl
0                 2         50
1                 4         58
2                 6         68
3                 8         80
4                10         92

## Optional: Interaktive Tabellenansicht in Google Colab

Diese Zelle funktioniert **nur in Google Colab**.  
In Jupyter wird stattdessen einfach das normale DataFrame angezeigt.

In [9]:
try:
    from google.colab import sheets
    sheets.InteractiveSheet(df=df)
except ImportError:
    print("Interaktive Tabellenansicht ist nur in Google Colab verfügbar.")
    display(df)

Interaktive Tabellenansicht ist nur in Google Colab verfügbar.

   Lernzeit_Stunden  Punktzahl
0                 2         50
1                 4         58
2                 6         68
3                 8         80
4                10         92

## Abschnitt 5 – Erste Visualisierung

Wir erstellen ein einfaches Liniendiagramm.  
Später werden wir im Kurs häufiger Streudiagramme verwenden.

In [10]:
plt.figure(figsize=(6, 4))
plt.plot(df["Lernzeit_Stunden"], df["Punktzahl"], marker="o")
plt.xlabel("Lernzeit in Stunden")
plt.ylabel("Punktzahl")
plt.title("Lernzeit und Punktzahl")
plt.grid(True)
plt.show()

NameError: name 'plt' is not defined

## Mini-Aufgaben

**Aufgabe 1:** Ändern Sie die Werte in `Lernzeit_Stunden`.  
Was passiert mit dem Diagramm?

**Aufgabe 2:** Fügen Sie eine weitere Zeile mit eigenen Werten zum DataFrame hinzu.

In [ ]:
# Aufgabe 2: Neue Zeile hinzufügen
# Ihr Code hier

**Aufgabe 3:** Erstellen Sie statt eines Liniendiagramms ein **Streudiagramm**.  
Hinweis: Verwenden Sie `plt.scatter()` statt `plt.plot()`.

In [ ]:
# Aufgabe 3: Streudiagramm
# Ihr Code hier

## Verständnisfragen

Beantworten Sie die folgenden Fragen in eigenen Worten:

1. Was ist der Unterschied zwischen einer Python-Liste und einem NumPy-Array?
2. Warum ist ein DataFrame für Datensätze oft praktischer als eine einfache Liste?